
version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/node_modules
    networks:
      - bugfix_network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PLANNER_URL=http://planner:8001
      - DEVELOPER_URL=http://developer:8002
      - QA_URL=http://qa:8003
      - COMMUNICATOR_URL=http://communicator:8004
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - TEST_COMMAND=python -m pytest
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
      - ./code_repo:/app/code_repo
      - ./backend:/app
    depends_on:
      - planner
      - developer
      - qa
      - communicator
    networks:
      - bugfix_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  planner:
    build:
      context: ./agents
      dockerfile: ./planner/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - TEST_COMMAND=python -m pytest
    env_file:
      - ./.env
    volumes:
      - ./code_repo:/app/code_repo
      - ./logs:/app/logs
    networks:
      - bugfix_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"] || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  developer:
    build:
      context: ./agents
      dockerfile: ./developer/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - MAX_RETRIES=${MAX_RETRIES:-4}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - TEST_COMMAND=python -m pytest
      - REPO_PATH=/app/code_repo
    env_file:
      - ./.env
    volumes:
      - ./code_repo:/app/code_repo
      - ./logs:/app/logs
    networks:
      - bugfix_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/"] || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  qa:
    build:
      context: ./agents
      dockerfile: ./qa/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TEST_COMMAND=python -m pytest
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - CODEBASE_PATH=/app/code_repo
      - REPO_PATH=/app/code_repo
    env_file:
      - ./.env
    volumes:
      - ./code_repo:/app/code_repo
      - ./logs:/app/logs
    networks:
      - bugfix_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/"] || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  communicator:
    build:
      context: ./agents
      dockerfile: ./communicator/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER}
      - GITHUB_REPO_NAME=${GITHUB_REPO_NAME}
      - GITHUB_DEFAULT_BRANCH=${GITHUB_DEFAULT_BRANCH:-main}
      - JIRA_TOKEN=${JIRA_TOKEN}
      - JIRA_USER=${JIRA_USER}
      - JIRA_URL=${JIRA_URL}
      - EMAIL_HOST=${EMAIL_HOST:-""}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER:-""}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-""}
      - SLACK_TOKEN=${SLACK_TOKEN:-""}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-""}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - TEST_COMMAND=python -m pytest
    env_file:
      - ./.env
    volumes:
      - ./code_repo:/app/code_repo
      - ./logs:/app/logs
      - ./backend/github_utils.py:/app/github_utils.py
    networks:
      - bugfix_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/"] || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  jira_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python -m jira_service.run_service
    environment:
      - JIRA_URL=${JIRA_URL}
      - JIRA_USER=${JIRA_USER}
      - JIRA_TOKEN=${JIRA_TOKEN}
      - JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY:-""}
      - JIRA_POLL_INTERVAL=${JIRA_POLL_INTERVAL:-30}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - TEST_COMMAND=python -m pytest
      - REPO_PATH=/app/code_repo
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs/jira_service
      - ./code_repo:/app/code_repo
    networks:
      - bugfix_network
    restart: unless-stopped

  github_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "echo 'Starting GitHub service...' && python -m github_service.test_service || echo 'GitHub service test completed with errors. Check the logs for details.'"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER}
      - GITHUB_REPO_NAME=${GITHUB_REPO_NAME}
      - GITHUB_DEFAULT_BRANCH=${GITHUB_DEFAULT_BRANCH:-main}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - TEST_COMMAND=python -m pytest
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs/github_service
      - ./code_repo:/app/code_repo
    networks:
      - bugfix_network
    restart: "no"

networks:
  bugfix_network:
    driver: bridge

volumes:
  code_repo:
  logs:
  node_modules:
